run:
  deadline: 2m

skip-files:
  - "pkg/version/bump_strategy_example_test.go"

linters:
  disable-all: true # explicit configuration is clearer
  enable:
    - govet
    # - errcheck this is a bit too much
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - revive
    - gocyclo
    - dupl
    - misspell
    - nakedret

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/arnaud-deprez/gsemver
  dupl:
    threshold: 400
  gocyclo:
    min-complexity: 15
