run:
  deadline: 2m

linters:
  disable-all: false
  enable:
    - gofmt
    - deadcode
    - dupl
    - misspell
    - nakedret
  disable:
    - errcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/arnaud-deprez/gsemver
  dupl:
    threshold: 400