version: "2"
linters:
  default: none
  enable:
    - dupl
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unused
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/arnaud-deprez/gsemver
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
