language: go

# This will allow usage of `git symbolic-ref HEAD`.
# Otherwise you can do `git fetch --unshallow` in the install step.
# More info: https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth
git:
  depth: false

go:
- 1.12.x
stages:
- Build
- Integration tests
- name: Release
  if: branch =~ ^master|release/.*$

env:
- GO111MODULE=on

jobs:
  include:
  - stage: Build
    script: make build test 
  - stage: Integration tests
    script: make test-integration
  - stage: Release
    name: "Prepare release"
    script: make release
  # - name: "Publish release"
  #   script: make publish