language: go

go:
- 1.14.x
stages:
- name: Build
  if: tag IS blank # because we create tag from this pipeline
- name: Tests
  if: tag IS blank # because we create tag from this pipeline
- name: Release
  if: branch =~ ^master|release/.*$ AND NOT type = pull_request

env:
  global:
  - GIT_AUTHOR_NAME="Arnaud Deprez"
  - GIT_AUTHOR_EMAIL="arnaudeprez@gmail.com"
  - GIT_COMMITTER_NAME="Arnaud Deprez"
  - GIT_COMMITTER_EMAIL="arnaudeprez@gmail.com"
  - GIT_BRANCH=${TRAVIS_BRANCH}
  - GIT_COMMIT=${TRAVIS_COMMIT}

jobs:
  include:
  - stage: Build
    script: make --environment-overrides test-release
  - stage: Tests
    script: 
      - make --environment-overrides test-integration
      - bash <(curl -s https://codecov.io/bash)
  - stage: Release
    script: make --environment-overrides release