language: go

go:
- 1.12.x
stages:
- Build
- Integration tests
- name: Release
  if: branch =~ ^master|release/.*$ AND NOT type = pull_request

env:
  global:
  - GO111MODULE=on
  - GIT_AUTHOR_NAME="Arnaud Deprez"
  - GIT_AUTHOR_EMAIL="arnaudeprez@gmail.com"
  - GIT_COMMITTER_NAME="Arnaud Deprez"
  - GIT_COMMITTER_EMAIL="arnaudeprez@gmail.com"
  - GIT_BRANCH=${TRAVIS_BRANCH}

jobs:
  include:
  - stage: Build
    script: make build test 
  - stage: Integration tests
    script: make test-integration
  - script: make test-release
  - stage: Release
    script: make release