name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      # needed to create commit or tag
      # see https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
      GIT_COMMITTER_NAME: "github-actions[bot]"
      GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Extract Branch Name in GIT_BRANCH env
        run: |
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF} & GITHUB_REF=${GITHUB_REF}"
          if [ -n "$GITHUB_HEAD_REF" ]
          then
            echo "GIT_BRANCH=${GITHUB_HEAD_REF#refs/heads/}" >> $GITHUB_ENV
          else
            echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Build
        run: make --environment-overrides test-release

      - name: Test
        run: make --environment-overrides test-integration

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make --environment-overrides release
        if: github.event_name != 'pull_request' && (github.ref_name == 'main' || startsWith(github.ref_name, 'release/'))
